# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# IntelliJ IDEA is not yet fully compatible with configuration cache, see: https://github.com/FabricMC/fabric-loom/issues/1349
org.gradle.configuration-cache=false

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=1.21.1
loader_version=0.19.3
loom_version=1.17-SNAPSHOT

# Mod Properties
mod_version=1.36.2
maven_group=dev.overgrown.apoli
maven_version=1.36.0+1.21.1-fabric

# Dependencies
fabric_api_version=0.116.15+1.21.1

icarus_version=4.7.6+Fabric

figura_version=ugF3NunW

trinkets_version=3.8.1

accessories_version=1.1.0-beta.53+1.21.1

balm_version=21.0.55+1.21.1

hardcore_revival_version=21.1.9+1.21.1

modmenu_version=11.0.3

skinlayers_version=IrL0IGkV

ears_version=rEnDH8t5

puffish_skills_version=hz4AXzIa

voicechat_api_version=2.6.0

vosk_version=0.3.45
